# Generated by Django 6.0 on 2026-09-09 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_location', models.CharField(max_length=255)),
                ('required_delivery_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('AWARDED', 'Awarded')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
